"""Write pair-specific source reviews and audit documentation; no measurements."""
from revise_preregistration import write
from validate_corpus import HERE, read

REVIEWS={
'direct_chain':('Both entries call one helper, then the increment target.','Rust attributes inhibit inlining; no application difference.','Only helper is directly called by entry and only target by helper.','Scalar arguments; no heap or callback state.'),
'recursion':('Both decrement an unsigned counter from two and call target at zero.','C unsigned and Rust u32 coincide for the prescribed small inputs.','recursive has its self-call and the base-case target call.','Recursion uses the stack; invocation count is not an application edge count.'),
'single_pointer':('Both store target in a local compatible callback then invoke it with ten.','C function pointer versus Rust fn value.','The sole assignment is target, so the site set is exactly {target}.','Local callback lives through invocation; no heap.'),
'multi_pointer':('Both select target_a or target_b from the same runtime boolean; main separately calls an unrelated pointer.','C argc versus Rust args supplies the selector; callback representations differ.','entry assigns only target_a/target_b. Harness-local unrelated is never passed to entry and has no shared state.','Two prescribed runs return 11 and 12; the separate live decoy call returns 13 in each run.'),
'first_field':('Both initialize first=target and second=other then call first.','C struct fields versus Rust Copy struct fields.','Only the first field is loaded: exactly {target}, excluding other.','Stack object with valid lifetime; no allocation.'),
'non_first_field':('Both initialize first=other and second=target then call second.','C field access versus Rust parenthesized fn field invocation.','Only second is loaded: exactly {target}, excluding other.','Stack object; second field index is one.'),
'stack_copy':('Both copy an object with first=other and second=target, then call copied.second.','C struct assignment versus Rust derived Copy.','Copy preserves second=target, so exactly {target}.','Original and copy are live stack values; no heap or alias mutation.'),
'heap_struct':('Both allocate an Ops object with first=other and second=target then invoke second.','C malloc/null check/free versus Rust Box allocation/drop.','Only heap second is called: exactly {target}; first cannot contribute.','Successful allocation is prescribed; allocation failure and allocator/drop internals legitimately differ.'),
'generic_specialization':('One C helper_i32 converts i32 to i64 and calls target; Rust helper::<i32> performs the matching conversion and call.','Rust Into<i64> may add core conversion transitions; C uses a cast.','Exactly one concrete Rust Instance realizes one generic source helper and corresponds to the one specialized C helper.','Scalar conversion only; one source observation, no heap and no multiple-instance claim.'),
'static_dispatch':('entry directly calls C operation / First::operation, which calls target; main separately calls the second operation.','Rust resolves a trait method on known First; C uses an ordinary function.','First is fixed at the tested call. Second::operation / second_operation is live only in main and never entry-reachable.','Direct calls only, no function pointer or vtable; harness second result is 13.'),
'dyn_vtable':('Both choose between two stack receivers and invoke a method through an object; main constructs and calls a separate third object.','C explicit context+method object versus Rust trait-object compiler vtable and possible shims.','entry receiver is exclusively First or Second; main-local Third is never passed to entry and writes no shared state.','All contexts outlive calls; Third vtable/pointer is materialized by its checked harness call returning 13. Both legitimate branches run.'),
'closure_context':('C callback takes an explicit offset environment; Rust closure captures the same offset; both call target on ten.','Rust closure call is static with compiler Fn/shim transitions; C uses a context callback pointer.','C site is exactly {callback}; Rust entry-to-closure and closure-to-target relations are declared, not a fabricated fn site.','Borrowed stack environment/offset remains valid during the call; no heap.'),
'library_callback':('Both sort [3,1,2] using target as comparator and check [1,2,3].','C qsort is an external body boundary; Rust sort_by has compiled generic std bodies and Ordering rather than int.','Both bind target as the library callback; no direct application entry-to-target edge is invented.','Stack arrays; comparator argument representations differ. Transitive library internals are outside external-boundary fields.'),
'mixed_stack_static':('Both pass a stack object and a static object to the same invoke function in explicit sequence.','C const static struct versus Rust static Copy struct and references.','second holds target_a on stack and target_b on static; unrelated stays in first, so site set is exactly both legitimate targets.','Stack/static lifetimes cover both calls; one default run checks sum 23.'),
'mixed_stack_heap':('Both pass stack and heap objects to the same invoke function in explicit sequence.','C malloc/free/null check versus Rust Box allocation/drop.','second holds target_a and target_b; unrelated is confined to first and cannot enter the site set.','Successful heap allocation is assumed; lifetimes cover both calls before free/drop; one run checks sum 23.')}

def main():
    m=read(HERE/'fixture_manifest.json')
    write(HERE/'source_review.json',{'review_basis':'Application source semantics only; independent re-audit pending','analyzer_outputs_consulted':False,
        'pairs':[{'pair_id':p['pair_id'],**dict(zip(('fair_analogue','legitimate_structural_difference','expected_target_set_rationale','storage_lifetime_runtime'),REVIEWS[p['pair_id']])),
            'decoy_non_flow_proof':p['special_semantics'].get('decoy'),'analyzer_outputs_consulted':False} for p in m['pairs']]})
    schema=read(HERE/'fixture_manifest.schema.json')
    schema['required']+=['semantic_extraction_configuration','revision_provenance','exact_application_structure_definition','external_boundary_definition']
    schema['properties']['semantic_extraction_configuration']={'type':'object','required':['C','Rust'],
        'properties':{k:{'type':'object','required':v} for k,v in {'C':['flags','target_policy','canonical_provider','helper_options','helper_sha256'],
            'Rust':['flags','canonical_configuration','driver','std_policy','codegen_units','target','edition','panic']}.items()}}
    write(HERE/'fixture_manifest.schema.json',schema)
    doc=HERE/'CALIBRATION_PREREGISTRATION.md'
    doc.write_text(doc.read_text()+'\n## Independent audit corrections R1-R5\n\n'
        +'Prior bundle `'+read(HERE/'revision_provenance.json')['prior_calibration_fixture_bundle_sha256']+'` is `superseded_before_measurement`, reason: `independent preregistration audit corrections R1-R5`. Its original sources, metadata, and hashes are archived in provenance. No analyzer output ever existed for it.\n\n'
        +'R1: Third::operation / third_operation is materialized and invoked through a separate trait object / context-method object in main. R2: unrelated is materialized and called through a separate same-signature pointer in main. R3: Second::operation / second_operation is directly called in main. Every decoy returns 13 and is checked in each prescribed run. None is passed to entry or writes shared state. Original entry bodies and target sets are unchanged. Decoy observations belong solely to the harness, outside the entry root.\n\n'
        +'R4 (expectation only): '+next(p['registered_relationship'] for p in m['pairs'] if p['pair_id']=='generic_specialization')+' Superseded wording is retained verbatim in revision_provenance.json and the archived preregistration.\n\n'
        +m['exact_application_structure_definition']+'\n\n'+m['external_boundary_definition']+'\n\n'
        +'R5: The manifest independently freezes Rust semantic extraction from the accepted cast-final-v2 canonical command argv and std configuration, fingerprinted in semantic_extraction_canonical.json. rustc 1.93.0, edition 2021, x86_64-unknown-linux-gnu, opt-level=0, codegen-units=1, panic=unwind, mir-opt-level=0, inline-mir=no, always-encode-mir, rebuilt-std noprelude extern and dependency flags, unstable-options, remap-path-prefix, -A dead_code and --emit=link are bound. The rustc_driver Probe configuration uses RUSTC_BOOTSTRAP=1, MIR_PROBE_TRANSITIVE=1 and Compilation::Stop; driver/compiler/library fingerprints and canonical build records are bound. No driver is executed in this pass.\n\n'
        +'C extraction freezes canonical backend DEFAULT_CFLAGS, debug path mappings, -emit-llvm -c, AndersenWaveDiff, and helper options -stat=false -ff-eq-base. Extraction intentionally uses the pinned compiler host-default x86_64-pc-linux-gnu target; smoke explicitly specifies the same triple. Full extraction and ordinary build configurations are separate manifest fields, both covered by the aggregate.\n\n'
        +'Pair-specific reviews describe analogue fairness, legitimate differences, target rationale, and storage/runtime distinctions. Source spans were recomputed from every definition/callsite anchor in all six edited sources. No analyzer or graph output was used.\n')

if __name__=='__main__':main()
