[
  {
    "name": "ollama_chat/qwen3.8:27b",
    "use_repo_map": false,
    "extra_params": {
      "temperature": 1.0,
      "think": "low",
      "seed": 42,
      "max_tokens": 65536,
      "num_ctx": 65536
    }
  },
  {
    "name": "ollama_chat/qwen3-coder-next:latest",
    "use_repo_map": false,
    "editor_edit_format": "whole",
    "extra_params": {
      "temperature": 0.0,
      "seed": 0,
      "num_ctx": 65536
    }
  }
]
