#!/usr/bin/env python3
"""Measure implementation diversity across N-version C programs.

Given a set of C source files that implement the same specification (e.g.
independent LLM samples of ``mkdir``), this tool answers a narrower question
than generic code similarity: *how much does the implementation actually
differ*, at several levels that are each grounded in an established
similarity/clone-detection paradigm, so that the numbers are defensible in a
research write-up rather than an ad-hoc score.

Levels (see docs/diversity_methodology.md for the full citation list and the
"what each level contributes" interpretation contract):

  1. lexical    - normalized Levenshtein (Type-1/3 clones) + Type-2 token
                  winnowing/Jaccard fingerprints (CCFinder / MOSS paradigm).
  2. ast        - normalized tree edit distance over tree-sitter C parse
                  trees, computed with APTED.
  3. api        - Jaccard distance over the set of called functions
                  ("strategy" fingerprint), plus descriptive lizard
                  complexity stats (NOT used as a distance).
  4. attack     - Jaccard/cosine distance over a small vector of
                  security-relevant syntactic constructs (unsafe string
                  calls, bounded-but-risky calls, fixed-size stack buffers,
                  heap calls, indexing operations) - the level that speaks
                  most directly to exploit non-transferability.
  5. neural     - optional (--neural): symmetrized 1-CodeBLEU and code-model
                  embedding cosine distance. Heavier deps (torch,
                  transformers, codebleu); reported as a literature
                  comparability point, not load-bearing for the other
                  levels.

Every level is reported as its own N x N distance matrix; this tool does not
compute a single weighted "diversity score" (see methodology doc for why).

Usage:
    python3 scripts/measure_diversity.py FILE_OR_GLOB [FILE_OR_GLOB ...] \\
        [--reference PATH] [--neural] [--out-dir DIR] [--calibrate]
"""

from __future__ import annotations

import argparse
import glob
import hashlib
import itertools
import json
import re
import statistics
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Iterable, Mapping, Sequence

REPO_ROOT = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------------------
# Optional dependency loading
# ---------------------------------------------------------------------------


def _import(name: str, pip_hint: str | None = None) -> Any:
    try:
        return __import__(name)
    except ImportError as exc:  # pragma: no cover - environment dependent
        hint = pip_hint or name
        raise SystemExit(
            f"Missing Python package '{name}'.\n"
            f"Install it with: python3 -m pip install {hint}\n"
            f"(original error: {exc})"
        )


def _tree_sitter_c_language() -> Any:
    from tree_sitter import Language

    import tree_sitter_c as tsc

    try:
        return Language(tsc.language())
    except TypeError:
        # Older tree-sitter (<0.22) needs a two-arg form.
        return Language(tsc.language(), "c")


def _make_parser() -> Any:
    from tree_sitter import Parser

    language = _tree_sitter_c_language()
    try:
        return Parser(language)
    except TypeError:
        parser = Parser()
        parser.set_language(language)
        return parser


_PARSER_CACHE: Any = None


def get_parser() -> Any:
    global _PARSER_CACHE
    if _PARSER_CACHE is None:
        _import("tree_sitter", "tree-sitter")
        _import("tree_sitter_c", "tree-sitter-c")
        _PARSER_CACHE = _make_parser()
    return _PARSER_CACHE


# ---------------------------------------------------------------------------
# Loading variants
# ---------------------------------------------------------------------------


@dataclass
class Variant:
    label: str
    path: Path
    source: bytes

    @property
    def text(self) -> str:
        return self.source.decode("utf-8", errors="replace")


def derive_label(path: Path, all_paths: Sequence[Path]) -> str:
    """Pick a short, human-legible, unique label for a variant path.

    Prefers a distinguishing ancestor directory (e.g. a ``temp-0p2`` run
    directory) over the bare filename, since files generated by the
    pipeline are almost always named identically (``new_mkdir.c``) across
    variants and it's the run directory that distinguishes them. But if
    the filename *stems* are already distinctive across the whole input
    set (e.g. vendored anchors like ``gnu_coreutils_mkdir.c`` vs
    ``busybox_mkdir.c``, all sitting in one directory), prefer the stem -
    it is more informative than a repeated parent directory name.
    """
    parts = path.parts
    temp_dirs = [p for p in parts if re.match(r"^temp-[0-9p]+$", p)]
    if temp_dirs:
        return temp_dirs[-1]

    stems = [p.stem for p in all_paths]
    if len(set(stems)) == len(stems):
        return path.stem

    # Fall back to the parent directory name, then the stem.
    if path.parent.name and path.parent.name not in (".", ""):
        return path.parent.name
    return path.stem


def load_variants(patterns: Sequence[str]) -> list[Variant]:
    paths: list[Path] = []
    for pattern in patterns:
        matches = sorted(Path(p) for p in glob.glob(pattern, recursive=True))
        if not matches and Path(pattern).exists():
            matches = [Path(pattern)]
        if not matches:
            raise SystemExit(f"No files matched: {pattern}")
        paths.extend(matches)

    # De-duplicate while preserving order.
    seen: set[Path] = set()
    unique_paths: list[Path] = []
    for p in paths:
        resolved = p.resolve()
        if resolved not in seen:
            seen.add(resolved)
            unique_paths.append(p)

    labels_seen: dict[str, int] = {}
    variants: list[Variant] = []
    for p in unique_paths:
        label = derive_label(p, unique_paths)
        if label in labels_seen:
            labels_seen[label] += 1
            label = f"{label}#{labels_seen[label]}"
        else:
            labels_seen[label] = 0
        variants.append(Variant(label=label, path=p, source=p.read_bytes()))
    return variants


# ---------------------------------------------------------------------------
# Tree-sitter parsing helpers
# ---------------------------------------------------------------------------


def tree_sitter_function_name(node: Any, data: bytes) -> str | None:
    """Extract a function definition's identifier name.

    Ported from scripts/analyze_experiment.py (pure function, no
    dependency on that module's larger pipeline).
    """
    declarator = node.child_by_field_name("declarator")
    if declarator is None:
        return None
    stack = [declarator]
    while stack:
        current = stack.pop()
        if current.type == "identifier":
            return data[current.start_byte : current.end_byte].decode(
                "utf-8", errors="replace"
            )
        stack.extend(reversed(current.children))
    return None


def tree_sitter_call_name(node: Any, data: bytes) -> str | None:
    """Extract a call_expression's callee identifier name.

    Ported from scripts/analyze_experiment.py.
    """
    function = node.child_by_field_name("function")
    if function is None:
        return None
    if function.type == "identifier":
        return data[function.start_byte : function.end_byte].decode(
            "utf-8", errors="replace"
        )
    return None


@dataclass
class ParsedSource:
    root: Any
    data: bytes


_PARSE_CACHE: dict[bytes, ParsedSource] = {}


def parse_source(source: bytes) -> ParsedSource:
    key = hashlib.sha256(source).digest()
    cached = _PARSE_CACHE.get(key)
    if cached is not None:
        return cached
    parser = get_parser()
    tree = parser.parse(source)
    parsed = ParsedSource(root=tree.root_node, data=source)
    _PARSE_CACHE[key] = parsed
    return parsed


def iter_nodes(node: Any) -> Iterable[Any]:
    stack = [node]
    while stack:
        current = stack.pop()
        yield current
        stack.extend(reversed(current.children))


# ---------------------------------------------------------------------------
# Level 1: lexical / token similarity
# ---------------------------------------------------------------------------


def strip_comments(parsed: ParsedSource) -> str:
    """Remove tree-sitter 'comment' node spans, collapse whitespace."""
    data = parsed.data
    comment_spans = [
        (n.start_byte, n.end_byte)
        for n in iter_nodes(parsed.root)
        if n.type == "comment"
    ]
    comment_spans.sort()
    out = bytearray()
    cursor = 0
    for start, end in comment_spans:
        out += data[cursor:start]
        cursor = end
    out += data[cursor:]
    text = out.decode("utf-8", errors="replace")
    return re.sub(r"\s+", " ", text).strip()


def normalized_levenshtein_similarity(a: ParsedSource, b: ParsedSource) -> float:
    rapidfuzz = _import("rapidfuzz", "rapidfuzz")
    from rapidfuzz.fuzz import ratio as levenshtein_ratio

    return levenshtein_ratio(strip_comments(a), strip_comments(b)) / 100.0


_LEAF_LITERAL_TYPES = {
    "number_literal": "NUM",
    "string_literal": "STR",
    "char_literal": "CHAR",
}


def type2_token_stream(parsed: ParsedSource) -> list[str]:
    """CCFinder-style Type-2 normalized token stream.

    Identifiers and literals are rewritten to a class placeholder;
    keywords, operators and punctuation are kept verbatim. This is what
    makes the resulting similarity invariant to identifier renaming and
    literal-value changes while still being sensitive to structure and
    vocabulary (which keywords/operators are used).
    """
    tokens: list[str] = []
    data = parsed.data
    for node in iter_nodes(parsed.root):
        if node.children or node.type == "comment":
            continue
        if node.type == "identifier":
            tokens.append("ID")
        elif node.type in _LEAF_LITERAL_TYPES:
            tokens.append(_LEAF_LITERAL_TYPES[node.type])
        else:
            tokens.append(node.type)
    return tokens


def winnowing_fingerprints(tokens: Sequence[str], k: int = 5, w: int = 4) -> set[int]:
    """Schleimer/Wilkerson/Aiken (SIGMOD 2003) winnowing fingerprint set.

    k = k-gram length in tokens, w = window size in hashes. Standard
    winnowing: within each window of k-gram hashes, select the minimum
    (rightmost on ties), de-duplicating consecutively repeated selections
    at the same position.
    """
    if len(tokens) < k:
        k = max(1, len(tokens))
    grams = [
        tuple(tokens[i : i + k]) for i in range(0, max(1, len(tokens) - k + 1))
    ]
    hashes = [
        int.from_bytes(
            hashlib.sha1("\x1f".join(g).encode("utf-8")).digest()[:8], "big"
        )
        for g in grams
    ]
    if not hashes:
        return set()

    fingerprints: set[int] = set()
    last_selected_index = -1
    for start in range(0, max(1, len(hashes) - w + 1)):
        window = hashes[start : start + w] or hashes[start:]
        min_value = min(window)
        # Rightmost occurrence of the minimum in this window.
        min_index_in_window = max(
            i for i, v in enumerate(window) if v == min_value
        )
        min_index = start + min_index_in_window
        if min_index != last_selected_index:
            fingerprints.add(hashes[min_index])
            last_selected_index = min_index
    return fingerprints


def jaccard(a: set[Any], b: set[Any]) -> float:
    if not a and not b:
        return 1.0
    union = a | b
    if not union:
        return 1.0
    return len(a & b) / len(union)


def token_winnowing_similarity(a: ParsedSource, b: ParsedSource) -> float:
    fp_a = winnowing_fingerprints(type2_token_stream(a))
    fp_b = winnowing_fingerprints(type2_token_stream(b))
    return jaccard(fp_a, fp_b)


# ---------------------------------------------------------------------------
# Level 2: AST / structural similarity (APTED tree edit distance)
# ---------------------------------------------------------------------------


class ASTTooLargeError(RuntimeError):
    """Raised when a parse tree exceeds MAX_AST_NODES; TED's cost blows up
    much faster than linearly in tree size for large/dissimilar trees, so
    this is a deliberate safety valve rather than a bug."""


MAX_AST_NODES = 20_000


def _to_apted_tree(node: Any) -> Any:
    # Only *named* nodes go into the tree (tree-sitter's term for
    # syntactically meaningful nodes - identifiers, expressions,
    # statements, ...), excluding anonymous punctuation/keyword leaves
    # (`(`, `;`, `{`, ...) and comments. This is what "AST" conventionally
    # means (as opposed to a full concrete/parse tree) and, as a large
    # side benefit, keeps trees small enough for APTED to be tractable:
    # an unfiltered concrete-syntax tree can be 1.5-2x the named-node
    # count but take orders of magnitude longer to align.
    from apted.helpers import Tree

    children = [
        _to_apted_tree(c)
        for c in node.children
        if c.is_named and c.type != "comment"
    ]
    return Tree(node.type, *children)


def _tree_size(node: Any) -> int:
    total = 0
    for n in iter_nodes(node):
        if not n.is_named or n.type == "comment":
            continue
        total += 1
    return total


def ast_tree_edit_similarity(a: ParsedSource, b: ParsedSource) -> float:
    _import("apted", "apted")
    from apted import APTED, Config

    size_a, size_b = _tree_size(a.root), _tree_size(b.root)
    if size_a > MAX_AST_NODES or size_b > MAX_AST_NODES:
        raise ASTTooLargeError(
            f"AST too large for exact tree edit distance "
            f"({size_a} / {size_b} named nodes, limit {MAX_AST_NODES}); "
            "skipped (see docs/diversity_methodology.md scalability note)."
        )
    tree_a = _to_apted_tree(a.root)
    tree_b = _to_apted_tree(b.root)
    ted = APTED(tree_a, tree_b, Config()).compute_edit_distance()
    max_size = max(size_a, size_b, 1)
    return max(0.0, 1.0 - ted / max_size)


# ---------------------------------------------------------------------------
# Level 3: API / call-set + descriptive complexity
# ---------------------------------------------------------------------------


def call_set(parsed: ParsedSource) -> set[str]:
    calls: set[str] = set()
    for node in iter_nodes(parsed.root):
        if node.type == "call_expression":
            name = tree_sitter_call_name(node, parsed.data)
            if name:
                calls.add(name)
    return calls


def call_set_similarity(a: ParsedSource, b: ParsedSource) -> float:
    return jaccard(call_set(a), call_set(b))


def lizard_metrics(path: Path) -> dict[str, float] | None:
    import shutil
    import subprocess

    executable = shutil.which("lizard")
    if executable is None:
        # Fall back to the running interpreter's own venv bin/ - `lizard`
        # is a Python console-script, so it lives next to sys.executable
        # even when the venv hasn't been `activate`d (PATH untouched).
        candidate = Path(sys.executable).with_name("lizard")
        if candidate.exists():
            executable = str(candidate)
    if executable is None:
        return None
    result = subprocess.run(
        [executable, "--csv", str(path)],
        capture_output=True,
        text=True,
        timeout=60,
    )
    if result.returncode != 0:
        return None
    import csv
    import io

    totals = {
        "function_count": 0.0,
        "total_nloc": 0.0,
        "total_cyclomatic_complexity": 0.0,
        "total_token_count": 0.0,
        "max_cyclomatic_complexity": 0.0,
        "max_function_length": 0.0,
    }
    for row in csv.reader(io.StringIO(result.stdout)):
        if len(row) < 8:
            continue
        try:
            nloc, complexity, tokens, _params, length = (
                float(row[0]),
                float(row[1]),
                float(row[2]),
                row[3],
                float(row[4]),
            )
        except ValueError:
            continue
        totals["function_count"] += 1
        totals["total_nloc"] += nloc
        totals["total_cyclomatic_complexity"] += complexity
        totals["total_token_count"] += tokens
        totals["max_cyclomatic_complexity"] = max(
            totals["max_cyclomatic_complexity"], complexity
        )
        totals["max_function_length"] = max(
            totals["max_function_length"], length
        )
    return totals


# ---------------------------------------------------------------------------
# Level 4: attack-surface / security-relevant construct profile
# ---------------------------------------------------------------------------

UNSAFE_CALLS = {"strcpy", "strcat", "sprintf", "gets", "vsprintf"}
BOUNDED_RISKY_CALLS = {
    "strncpy",
    "strncat",
    "snprintf",
    "memcpy",
    "memmove",
    "stpcpy",
}
HEAP_CALLS = {"malloc", "calloc", "realloc", "free", "strdup", "reallocarray"}

ATTACK_SURFACE_CATEGORIES = (
    "unsafe_calls",
    "bounded_risky_calls",
    "heap_calls",
    "fixed_stack_buffers",
    "indexing_ops",
)


def _is_fixed_size_array_declarator(node: Any, data: bytes) -> bool:
    """True for e.g. ``char buf[PATH_MAX];`` / ``char buf[64];`` -
    a local array declarator whose size is a literal or a (presumably
    constant) identifier, as opposed to a variable-length/pointer form.
    """
    if node.type != "array_declarator":
        return False
    size = node.child_by_field_name("size")
    return size is not None and size.type in ("number_literal", "identifier")


def attack_surface_vector(parsed: ParsedSource) -> dict[str, int]:
    counts = {c: 0 for c in ATTACK_SURFACE_CATEGORIES}
    for node in iter_nodes(parsed.root):
        if node.type == "call_expression":
            name = tree_sitter_call_name(node, parsed.data)
            if name in UNSAFE_CALLS:
                counts["unsafe_calls"] += 1
            elif name in BOUNDED_RISKY_CALLS:
                counts["bounded_risky_calls"] += 1
            elif name in HEAP_CALLS:
                counts["heap_calls"] += 1
        elif node.type == "array_declarator":
            if _is_fixed_size_array_declarator(node, parsed.data):
                counts["fixed_stack_buffers"] += 1
        elif node.type == "subscript_expression":
            counts["indexing_ops"] += 1
    return counts


def _cosine(a: Sequence[float], b: Sequence[float]) -> float:
    dot = sum(x * y for x, y in zip(a, b))
    norm_a = sum(x * x for x in a) ** 0.5
    norm_b = sum(y * y for y in b) ** 0.5
    if norm_a == 0.0 and norm_b == 0.0:
        return 1.0
    if norm_a == 0.0 or norm_b == 0.0:
        return 0.0
    return dot / (norm_a * norm_b)


def attack_surface_similarity(a: ParsedSource, b: ParsedSource) -> float:
    va = attack_surface_vector(a)
    vb = attack_surface_vector(b)
    vec_a = [va[c] for c in ATTACK_SURFACE_CATEGORIES]
    vec_b = [vb[c] for c in ATTACK_SURFACE_CATEGORIES]
    cosine_sim = _cosine(vec_a, vec_b)
    present_a = {c for c in ATTACK_SURFACE_CATEGORIES if va[c] > 0}
    present_b = {c for c in ATTACK_SURFACE_CATEGORIES if vb[c] > 0}
    jaccard_sim = jaccard(present_a, present_b)
    # Average the scale-sensitive (cosine) and presence-only (Jaccard)
    # views; both are reported individually in per-variant diagnostics.
    return (cosine_sim + jaccard_sim) / 2.0


# ---------------------------------------------------------------------------
# Level 5: neural / learned similarity (optional)
# ---------------------------------------------------------------------------

_EMBEDDING_MODEL_CACHE: dict[str, tuple[Any, Any]] = {}


def codebleu_similarity(a_text: str, b_text: str) -> float:
    codebleu_mod = _import("codebleu", "codebleu")
    calc_codebleu = codebleu_mod.calc_codebleu
    # CodeBLEU is reference-based (asymmetric n-gram precision direction);
    # symmetrize by averaging both directions.
    forward = calc_codebleu([a_text], [b_text], lang="c")["codebleu"]
    backward = calc_codebleu([b_text], [a_text], lang="c")["codebleu"]
    return (forward + backward) / 2.0


def _load_embedding_model(model_name: str) -> tuple[Any, Any]:
    if model_name in _EMBEDDING_MODEL_CACHE:
        return _EMBEDDING_MODEL_CACHE[model_name]
    torch = _import("torch", "torch")
    transformers = _import("transformers", "transformers")
    tokenizer = transformers.AutoTokenizer.from_pretrained(model_name)
    model = transformers.AutoModel.from_pretrained(model_name)
    model.eval()
    _EMBEDDING_MODEL_CACHE[model_name] = (tokenizer, model)
    return tokenizer, model


def embed(text: str, model_name: str) -> Any:
    torch = _import("torch", "torch")
    tokenizer, model = _load_embedding_model(model_name)
    inputs = tokenizer(
        text, return_tensors="pt", truncation=True, max_length=512
    )
    with torch.no_grad():
        outputs = model(**inputs)
    hidden = outputs.last_hidden_state[0]
    mask = inputs["attention_mask"][0].unsqueeze(-1).float()
    pooled = (hidden * mask).sum(0) / mask.sum().clamp(min=1.0)
    return pooled


def embedding_similarity(a_text: str, b_text: str, model_name: str) -> float:
    torch = _import("torch", "torch")
    ea = embed(a_text, model_name)
    eb = embed(b_text, model_name)
    sim = torch.nn.functional.cosine_similarity(ea.unsqueeze(0), eb.unsqueeze(0))
    return float(sim.item())


# ---------------------------------------------------------------------------
# Metric registry
# ---------------------------------------------------------------------------


@dataclass
class Metric:
    key: str
    name: str
    level: str
    fn: Callable[[Variant, Variant], float]
    requires: tuple[str, ...] = ()


def _metric_lexical_levenshtein(a: Variant, b: Variant) -> float:
    return normalized_levenshtein_similarity(parse_source(a.source), parse_source(b.source))


def _metric_lexical_winnowing(a: Variant, b: Variant) -> float:
    return token_winnowing_similarity(parse_source(a.source), parse_source(b.source))


def _metric_ast_ted(a: Variant, b: Variant) -> float:
    return ast_tree_edit_similarity(parse_source(a.source), parse_source(b.source))


def _metric_api_callset(a: Variant, b: Variant) -> float:
    return call_set_similarity(parse_source(a.source), parse_source(b.source))


def _metric_attack_surface(a: Variant, b: Variant) -> float:
    return attack_surface_similarity(parse_source(a.source), parse_source(b.source))


def _metric_codebleu(a: Variant, b: Variant) -> float:
    return codebleu_similarity(a.text, b.text)


def _metric_embedding(a: Variant, b: Variant, model_name: str) -> float:
    return embedding_similarity(a.text, b.text, model_name)


def build_classical_metrics() -> list[Metric]:
    return [
        Metric(
            "lexical_levenshtein",
            "Normalized Levenshtein (comment-stripped)",
            "lexical",
            _metric_lexical_levenshtein,
        ),
        Metric(
            "lexical_winnowing",
            "Type-2 token winnowing Jaccard (MOSS-style)",
            "lexical",
            _metric_lexical_winnowing,
        ),
        Metric(
            "ast_ted",
            "Normalized AST tree edit distance similarity (APTED)",
            "ast",
            _metric_ast_ted,
        ),
        Metric(
            "api_callset",
            "Called-function set Jaccard similarity",
            "api",
            _metric_api_callset,
        ),
        Metric(
            "attack_surface",
            "Security-construct profile similarity",
            "attack",
            _metric_attack_surface,
        ),
    ]


def build_neural_metrics(embedding_model: str) -> list[Metric]:
    return [
        Metric("neural_codebleu", "Symmetrized CodeBLEU", "neural", _metric_codebleu),
        Metric(
            "neural_embedding",
            f"Embedding cosine similarity ({embedding_model})",
            "neural",
            lambda a, b: _metric_embedding(a, b, embedding_model),
        ),
    ]


# ---------------------------------------------------------------------------
# Pairwise computation & aggregation
# ---------------------------------------------------------------------------


def compute_pairwise(
    variants: Sequence[Variant], metric: Metric
) -> dict[tuple[str, str], float]:
    result: dict[tuple[str, str], float] = {}
    for v in variants:
        result[(v.label, v.label)] = 1.0
    for a, b in itertools.combinations(variants, 2):
        try:
            sim = metric.fn(a, b)
        except ASTTooLargeError as exc:
            print(f"  warning: {metric.key}({a.label}, {b.label}): {exc}", file=sys.stderr)
            sim = float("nan")
        result[(a.label, b.label)] = sim
        result[(b.label, a.label)] = sim
    return result


def matrix_rows(
    variants: Sequence[Variant], pairwise: Mapping[tuple[str, str], float]
) -> list[list[float]]:
    labels = [v.label for v in variants]
    return [[pairwise[(a, b)] for b in labels] for a in labels]


def upper_triangle(
    variants: Sequence[Variant], pairwise: Mapping[tuple[str, str], float]
) -> list[float]:
    labels = [v.label for v in variants]
    return [pairwise[(a, b)] for a, b in itertools.combinations(labels, 2)]


def write_matrix_csv(
    path: Path, variants: Sequence[Variant], pairwise: Mapping[tuple[str, str], float]
) -> None:
    import csv

    labels = [v.label for v in variants]
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow([""] + labels)
        for a in labels:
            writer.writerow([a] + [f"{pairwise[(a, b)]:.6f}" for b in labels])


def set_summary(values: Sequence[float]) -> dict[str, float | None]:
    if not values:
        return {"mean": None, "min": None, "max": None, "stdev": None}
    return {
        "mean": statistics.mean(values),
        "min": min(values),
        "max": max(values),
        "stdev": statistics.stdev(values) if len(values) > 1 else 0.0,
    }


# ---------------------------------------------------------------------------
# Figures
# ---------------------------------------------------------------------------


def plot_heatmap(
    path: Path,
    labels: Sequence[str],
    matrix: Sequence[Sequence[float]],
    title: str,
) -> None:
    _import("matplotlib", "matplotlib")
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import numpy as np

    label_pad = max((len(l) for l in labels), default=8) * 0.11
    side = max(4.5, 1.6 + 0.7 * len(labels) + label_pad)
    fig, ax = plt.subplots(figsize=(side, side), constrained_layout=True)
    arr = np.array(matrix)
    im = ax.imshow(arr, vmin=0.0, vmax=1.0, cmap="viridis")
    ax.set_xticks(range(len(labels)))
    ax.set_yticks(range(len(labels)))
    ax.set_xticklabels(labels, rotation=45, ha="right", fontsize=8)
    ax.set_yticklabels(labels, fontsize=8)
    for i in range(len(labels)):
        for j in range(len(labels)):
            ax.text(
                j,
                i,
                f"{arr[i, j]:.2f}",
                ha="center",
                va="center",
                color="white" if arr[i, j] < 0.6 else "black",
                fontsize=8,
            )
    ax.set_title(title, fontsize=10, wrap=True)
    fig.colorbar(im, ax=ax, shrink=0.8, label="similarity")
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=150)
    plt.close(fig)


def plot_distance_distribution(
    path: Path, per_level_similarities: Mapping[str, Sequence[float]]
) -> None:
    _import("matplotlib", "matplotlib")
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    levels = list(per_level_similarities)
    fig, ax = plt.subplots(figsize=(6, 4))
    data = [[1.0 - s for s in per_level_similarities[level]] for level in levels]
    try:
        ax.boxplot(data, tick_labels=levels, vert=True)
    except TypeError:  # matplotlib < 3.9 uses the old kwarg name
        ax.boxplot(data, labels=levels, vert=True)
    ax.set_ylabel("pairwise distance (1 - similarity)")
    ax.set_title("Pairwise distance distribution by level")
    ax.set_ylim(-0.05, 1.05)
    plt.setp(ax.get_xticklabels(), rotation=30, ha="right")
    fig.tight_layout()
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=150)
    plt.close(fig)


def plot_cross_level_correlation(
    path: Path, level_names: Sequence[str], corr_matrix: Sequence[Sequence[float]]
) -> None:
    _import("matplotlib", "matplotlib")
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import numpy as np

    label_pad = max((len(l) for l in level_names), default=8) * 0.11
    side = max(4.5, 1.6 + 0.7 * len(level_names) + label_pad)
    fig, ax = plt.subplots(figsize=(side, side), constrained_layout=True)
    arr = np.array(corr_matrix)
    im = ax.imshow(arr, vmin=-1.0, vmax=1.0, cmap="coolwarm")
    ax.set_xticks(range(len(level_names)))
    ax.set_yticks(range(len(level_names)))
    ax.set_xticklabels(level_names, rotation=45, ha="right", fontsize=8)
    ax.set_yticklabels(level_names, fontsize=8)
    for i in range(len(level_names)):
        for j in range(len(level_names)):
            ax.text(
                j, i, f"{arr[i, j]:.2f}", ha="center", va="center", fontsize=8
            )
    ax.set_title("Spearman correlation between level distances", fontsize=10)
    fig.colorbar(im, ax=ax, shrink=0.8)
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=150)
    plt.close(fig)


# ---------------------------------------------------------------------------
# Clustering
# ---------------------------------------------------------------------------


def cluster_variants(
    variants: Sequence[Variant],
    pairwise: Mapping[tuple[str, str], float],
    threshold: float,
) -> dict[str, Any]:
    if len(variants) < 3:
        return {"skipped": "need >=3 variants for clustering"}
    _import("numpy", "numpy")
    _import("sklearn", "scikit-learn")
    import numpy as np
    from sklearn.cluster import AgglomerativeClustering
    from sklearn.metrics import silhouette_score

    labels = [v.label for v in variants]
    dist = np.array(
        [[1.0 - pairwise[(a, b)] for b in labels] for a in labels]
    )
    if np.isnan(dist).any():
        return {"skipped": "one or more pairwise distances is NaN (see warnings above)"}
    np.fill_diagonal(dist, 0.0)
    model = AgglomerativeClustering(
        metric="precomputed",
        linkage="average",
        distance_threshold=threshold,
        n_clusters=None,
    )
    assignment = model.fit_predict(dist)
    n_clusters = len(set(assignment))
    result: dict[str, Any] = {
        "distance_threshold": threshold,
        "n_clusters": n_clusters,
        "assignment": {label: int(c) for label, c in zip(labels, assignment)},
    }
    if 2 <= n_clusters <= len(variants) - 1:
        result["silhouette"] = float(
            silhouette_score(dist, assignment, metric="precomputed")
        )
    else:
        result["silhouette"] = None
    return result


# ---------------------------------------------------------------------------
# Cross-level correlation
# ---------------------------------------------------------------------------


def cross_level_correlation(
    level_vectors: Mapping[str, Sequence[float]]
) -> tuple[list[str], list[list[float]]]:
    _import("scipy", "scipy")
    from scipy.stats import spearmanr

    names = list(level_vectors)
    matrix = [[0.0] * len(names) for _ in names]
    for i, ni in enumerate(names):
        for j, nj in enumerate(names):
            if i == j:
                matrix[i][j] = 1.0
                continue
            vi, vj = level_vectors[ni], level_vectors[nj]
            if len(vi) < 2 or len(set(vi)) < 2 or len(set(vj)) < 2:
                matrix[i][j] = float("nan")
                continue
            corr, _p = spearmanr(vi, vj)
            matrix[i][j] = float(corr)
    return names, matrix


# ---------------------------------------------------------------------------
# Calibration controls
# ---------------------------------------------------------------------------

_CALIBRATION_FIXTURE = b"""\
#include <stdio.h>
#include <string.h>

static int add_one(int value) {
    int result = value + 1;
    return result;
}

int main(int argc, char *argv[]) {
    char buffer[64];
    strncpy(buffer, argv[0], sizeof(buffer) - 1);
    buffer[sizeof(buffer) - 1] = '\\0';
    int total = add_one(41);
    printf("%s says %d\\n", buffer, total);
    return 0;
}
"""


def _rename_identifiers(source: bytes) -> bytes:
    """Produce a Type-2-clone control: every identifier token is renamed
    to a distinct, deterministic placeholder while everything else
    (structure, literals, keywords, operators) is left untouched."""
    parsed = parse_source(source)
    renames: dict[str, str] = {}
    counter = itertools.count(1)

    edits: list[tuple[int, int, bytes]] = []
    for node in iter_nodes(parsed.root):
        if node.type == "identifier" and not node.children:
            original = parsed.data[node.start_byte : node.end_byte].decode("utf-8")
            if original not in renames:
                renames[original] = f"v{next(counter)}"
            edits.append((node.start_byte, node.end_byte, renames[original].encode()))

    edits.sort(key=lambda e: e[0])
    out = bytearray()
    cursor = 0
    for start, end, replacement in edits:
        out += source[cursor:start]
        out += replacement
        cursor = end
    out += source[cursor:]
    return bytes(out)


def run_calibration() -> bool:
    """Run the identical-copy / renamed-copy sanity controls from the
    methodology's validity-controls section. Prints a pass/fail table and
    returns True iff every expectation held.
    """
    base = _CALIBRATION_FIXTURE
    renamed = _rename_identifiers(base)

    identical = Variant("base", Path("<calibration:base>"), base)
    identical_copy = Variant("base_copy", Path("<calibration:base_copy>"), base)
    renamed_copy = Variant("renamed", Path("<calibration:renamed>"), renamed)

    metrics = build_classical_metrics()
    ok = True
    print("Calibration: identical-copy control (expect ~1.0 at every level)")
    for m in metrics:
        sim = m.fn(identical, identical_copy)
        passed = sim > 0.999
        ok &= passed
        print(f"  [{'OK' if passed else 'FAIL'}] {m.key:22s} = {sim:.4f}")

    print(
        "\nCalibration: renamed-copy control "
        "(expect ast_ted & lexical_winnowing ~1.0, lexical_levenshtein < 1.0)"
    )
    expectations = {
        "lexical_levenshtein": lambda s: s < 0.999,
        "lexical_winnowing": lambda s: s > 0.999,
        "ast_ted": lambda s: s > 0.999,
        "api_callset": lambda s: True,  # renaming also renames call names; informational only
        "attack_surface": lambda s: True,
    }
    for m in metrics:
        sim = m.fn(identical, renamed_copy)
        check = expectations.get(m.key, lambda s: True)
        passed = check(sim)
        ok &= passed
        print(f"  [{'OK' if passed else 'FAIL'}] {m.key:22s} = {sim:.4f}")

    print(f"\nCalibration {'PASSED' if ok else 'FAILED'}.")
    return ok


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "inputs",
        nargs="*",
        help="C source files or globs to compare (e.g. runs/**/new_mkdir.c)",
    )
    parser.add_argument(
        "--reference",
        action="append",
        default=[],
        help="Extra reference file(s) to include in the comparison "
        "(e.g. an independent human implementation). Repeatable.",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=REPO_ROOT / "runs" / "diversity",
        help="Directory to write matrices/figures/summary.json to.",
    )
    parser.add_argument(
        "--neural",
        action="store_true",
        help="Also compute Level 5 neural metrics (CodeBLEU + embedding "
        "cosine). Requires torch/transformers/codebleu.",
    )
    parser.add_argument(
        "--embedding-model",
        default="microsoft/unixcoder-base",
        help="HuggingFace model id for the embedding metric.",
    )
    parser.add_argument(
        "--cluster-threshold",
        type=float,
        default=0.3,
        help="Distance threshold for agglomerative clustering (on 1-similarity).",
    )
    parser.add_argument(
        "--no-figures",
        action="store_true",
        help="Skip matplotlib figure generation (matrices/JSON still written).",
    )
    parser.add_argument(
        "--calibrate",
        action="store_true",
        help="Run sanity-check controls (identical/renamed copies) and exit.",
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)

    if args.calibrate:
        return 0 if run_calibration() else 1

    if not args.inputs and not args.reference:
        print("error: provide at least one input file/glob (or --calibrate)", file=sys.stderr)
        return 2

    variants = load_variants(list(args.inputs) + list(args.reference))
    if len(variants) < 2:
        print("error: need at least 2 variants to compare", file=sys.stderr)
        return 2

    print(f"Loaded {len(variants)} variant(s):")
    for v in variants:
        print(f"  {v.label:30s} {v.path}")

    metrics = build_classical_metrics()
    if args.neural:
        metrics += build_neural_metrics(args.embedding_model)

    out_dir: Path = args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    summary: dict[str, Any] = {
        "variants": [{"label": v.label, "path": str(v.path)} for v in variants],
        "levels": {},
    }

    # Each metric's pairwise matrix is computed exactly once here and
    # reused for the summary, clustering, cross-level correlation, and
    # plots below - some metrics (AST TED, neural embeddings) are
    # expensive enough per pair that recomputing them for each downstream
    # consumer would multiply runtime for no benefit.
    pairwise_by_metric: dict[str, dict[tuple[str, str], float]] = {}
    similarities_by_metric: dict[str, list[float]] = {}

    for metric in metrics:
        print(f"Computing {metric.key} ({metric.name})...")
        pairwise = compute_pairwise(variants, metric)
        pairwise_by_metric[metric.key] = pairwise
        write_matrix_csv(out_dir / f"{metric.key}.csv", variants, pairwise)
        sims = upper_triangle(variants, pairwise)
        similarities_by_metric[metric.key] = sims
        summary["levels"][metric.key] = {
            "name": metric.name,
            "level": metric.level,
            "similarity_summary": set_summary(sims),
            "distance_summary": set_summary([1.0 - s for s in sims]),
        }
        if not args.no_figures:
            plot_heatmap(
                out_dir / "figures" / f"{metric.key}_heatmap.png",
                [v.label for v in variants],
                matrix_rows(variants, pairwise),
                f"{metric.name}",
            )

    # Descriptive (non-distance) diagnostics: lizard complexity, per-variant
    # attack-surface vectors.
    summary["per_variant"] = {}
    for v in variants:
        parsed = parse_source(v.source)
        summary["per_variant"][v.label] = {
            "lizard": lizard_metrics(v.path)
            if v.path.exists()
            else None,
            "attack_surface_vector": attack_surface_vector(parsed),
            "call_set": sorted(call_set(parsed)),
            "size_bytes": len(v.source),
        }

    # Clustering per level (only levels with a genuine distance semantics).
    summary["clustering"] = {
        metric.key: cluster_variants(
            variants, pairwise_by_metric[metric.key], args.cluster_threshold
        )
        for metric in metrics
    }

    # Cross-level correlation.
    if len(variants) >= 3:
        level_names, corr_matrix = cross_level_correlation(similarities_by_metric)
        summary["cross_level_correlation"] = {
            "levels": level_names,
            "matrix": corr_matrix,
        }
        if not args.no_figures:
            plot_cross_level_correlation(
                out_dir / "figures" / "cross_level_correlation.png",
                level_names,
                corr_matrix,
            )
    else:
        summary["cross_level_correlation"] = {
            "skipped": "need >=3 variants for a meaningful correlation"
        }

    if not args.no_figures:
        plot_distance_distribution(
            out_dir / "figures" / "distance_distribution.png",
            similarities_by_metric,
        )

    summary_path = out_dir / "summary.json"
    summary_path.write_text(json.dumps(summary, indent=2, default=str))
    print(f"\nWrote matrices/figures/summary to {out_dir}")
    print(f"Summary: {summary_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
